/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Runtime caching for Bible API
registerRoute(
  /^https:\/\/query\.bibleget\.io\/v3\/.*/i,
  new CacheFirst({
    cacheName: 'bible-api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 1200,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Push notification handling
self.addEventListener('push', (event) => {
  if (event.data) {
    try {
      const data = event.data.json();
      const title = data.title || 'Versetto del giorno';
      const options = {
        body: data.body,
        icon: '/pwa-192x192.png',
        badge: '/pwa-64x64.png',
        data: {
          url: data.url || '/',
        },
      };

      event.waitUntil(self.registration.showNotification(title, options));
    } catch (e) {
      // Se non è JSON, mostriamo il testo semplice
      const text = event.data.text();
      event.waitUntil(
        self.registration.showNotification('Versetto del giorno', {
          body: text,
          icon: '/pwa-192x192.png',
        })
      );
    }
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  let urlToOpen = event.notification.data?.url || '/';
  if (urlToOpen.includes('#/reader/')) {
    urlToOpen += (urlToOpen.includes('?') ? '&' : '?') + 'source=notification';
  }
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        // Se c'è già una finestra aperta sul dominio, focheggiamo su quella
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(urlToOpen);
          return client.focus();
        }
      }
      // Se non ci sono finestre aperte, ne apriamo una nuova
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Ascolta il messaggio SKIP_WAITING per aggiornare il service worker senza aspettare la chiusura dell'app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
